### ISSUE TITLE
panic in subpixel_quantize_offset

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1047]
webrender_traits::font::{{impl}}::subpixel_quantize_offset(self=0x000000013b1656bd, pos=-3) + 183 at font.rs:66
   63  	            0.25...0.5 => SubpixelOffset::Quarter,
   64  	            0.5...0.75 => SubpixelOffset::Half,
   65  	            0.75...1.0 => SubpixelOffset::ThreeQuarters,
-> 66  	            _ => panic!("Should only be given the fractional part"),

**Comment by jrmuizel** [comment]
This happens because fract(-3+0.125) is negative.
@changm Where's the skia code the corresponds to this?

**Comment by changm** [comment]
It's over here - http://searchfox.org/mozilla-central/source/gfx/skia/skia/src/core/SkFindAndPlaceGlyph.h#383

Do you have a test case for this panic?

**Comment by kvark** [comment]
We could use `pos - pos.floor()` instead of `pos.fract()`

**Comment by jrmuizel** [comment]
You'll need #1071 to reproduce it in wrench and #1070 has VeraBd.ttf

```yaml
---
root: 
  items: 
        - 
          bounds: [14, 18, 205, 35]
          glyphs: [55]
          offsets: [-2, 43]
          size: 24
          color: black
          font: "VeraBd.ttf"
```
