### ISSUE TITLE
Rounded borders are not clipped properly

### ISSUE THREAD

**Issue by mrobinson** [servo/webrender#1102]
The follow wrench YAML does not show the bottom corners of the border clipped properly:

```yaml
---
root:
  items:
    - type: scroll-layer
      bounds: [0, 0, 100, 100]
      clip:
        rect: [0, 0, 100, 100]
        complex:
          - rect: [0, 0, 100, 100]
            radius:
              top-left: [0, 0]
              top-right: [0, 0]
              bottom-right: [30, 30]
              bottom-left: [30, 30]
      items:
        - type: border
          bounds: [0, 0, 100, 100]
          width: [5, 5, 5, 5]
          border-type: normal
          style: [solid, solid, solid, solid]
          color: [blue, blue, blue, blue]
          radius:
            top-left: [30, 30]
            top-right: [30, 30]
            bottom-right: [0, 0]
            bottom-left: [0, 0]
```

This seems to be an issue with the radius itself. Removing the radius on the border causes the corners to be clipped properly.
