### ISSUE TITLE
Webrender doesn't curve borders if both neighbours are invisible

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1291]
Here are two borders that should render the same (to the human eye) but don't in webrender:

![screen shot 2017-05-24 at 11 46 02 am](https://cloud.githubusercontent.com/assets/1136864/26412394/a2a0a5b8-4076-11e7-897c-a9041eb85e47.png)

left (incorrect render):
```
          bounds: [28, 18, 144, 122]
          clip: [-17895698, -17895698, 35791396, 35791396]
          "clip-and-scroll": 0
          type: border
          width: [18, 0, 18, 0]
          "border-type": normal
          color: 0 0 255 1.0000
          style:
            - solid
            - none
            - solid
            - none
          radius: [61, 61]
```

right (correct render):
```
          bounds: [192, 18, 144.03334, 122]
          clip: [-17895698, -17895698, 35791396, 35791396]
          "clip-and-scroll": 0
          type: border
          width: [18, 0.016666668, 18, 0.016666668]
          "border-type": normal
          color: 0 0 255 1.0000
          style: solid
          radius: [61, 61]
```

The problem is that webrender seems to give up on applying curvature if both neighbours (in this case left and right) have no rendered size. This can be accomplished by either `border-width: 0` or `style: none` -- in this case both.

This is seen in this gecko reftest: `layout/reftests/border-radius/corner-joins-1.xhtml` -- both servo and gecko feed webrender zero-size borders.
