### ISSUE TITLE
Implement blur filter

### ISSUE THREAD

**Issue by mrobinson** [servo/webrender#1351]
This can be observed by running the following wrench test:
```yaml
root:
  items:
    - type: stacking-context
      bounds: [10, 10, 500, 500]
      filters: blur(5)
      items:
        - type: rect
          bounds: [10, 10, 50, 50]
          color: green
```

cc @glennw @jrmuizel
