### ISSUE TITLE
Unexpected behavior when combining filters

### ISSUE THREAD

**Issue by mrobinson** [servo/webrender#1354]
I have observed that opacity filters do not combine as I would expect. For instance the two rectangles in the following wrench output are a different color:
```yaml
root:
  items:
    - type: stacking-context
      bounds: [10, 10, 500, 500]
      filters: [opacity(0.50), opacity(0.50)]
      items:
        - type: rect
          bounds: [10, 10, 100, 100]
          color: green
    - type: stacking-context
      bounds: [110, 10, 500, 500]
      filters: [opacity(0.25)]
      items:
        - type: rect
          bounds: [10, 10, 100, 100]
          color: green
```

![screenshot](https://user-images.githubusercontent.com/13536/26969368-c9e8c0e2-4d05-11e7-8cc4-a11b2c51cb78.png)
