### ISSUE TITLE
Shadows fade to black instead of transparent

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1373]
The following test case of a red shadow on top of a red rect fails with webrender:
```patch
commit 29b460935300f148bb4d433c689bbe87d7f215a7
Author: Jeff Muizelaar <jmuizelaar@mozilla.com>
Date:   Tue Jun 13 14:28:18 2017 -0400

    Add failing shadow test

diff --git a/wrench/reftests/text/reftest.list b/wrench/reftests/text/reftest.list
index ef98f6f..f2fd11c 100644
--- a/wrench/reftests/text/reftest.list
+++ b/wrench/reftests/text/reftest.list
@@ -1,4 +1,5 @@
 != text.yaml blank.yaml
 != negative-pos.yaml blank.yaml
 != shadow.yaml text.yaml
 != shadow-single.yaml blank.yaml
+== shadow-red.yaml shadow-red-ref.yaml
diff --git a/wrench/reftests/text/shadow-red-ref.yaml b/wrench/reftests/text/shadow-red-ref.yaml
new file mode 100644
index 0000000..6c2f50f
--- /dev/null
+++ b/wrench/reftests/text/shadow-red-ref.yaml
@@ -0,0 +1,5 @@
+---
+root:
+  items:
+        - rect: [14, 10, 205, 38]
+          color: red
diff --git a/wrench/reftests/text/shadow-red.yaml b/wrench/reftests/text/shadow-red.yaml
new file mode 100644
index 0000000..d770f2e
--- /dev/null
+++ b/wrench/reftests/text/shadow-red.yaml
@@ -0,0 +1,13 @@
+---
+root:
+  items:
+        - rect: [14, 10, 205, 38]
+          color: red
+        -
+          bounds: [14, 18, 205, 35]
+          glyphs: [55, 75, 76, 86, 3, 76, 86, 3, 87, 75, 72, 3, 69, 72, 86, 87]
+          offsets: [16, 43, 35.533333, 43, 51.533333, 43, 60.4, 43, 72.833336, 43, 80.833336, 43, 89.7, 43, 102.13333, 43, 110.13333, 43, 119, 43, 135, 43, 149.2, 43, 157.2, 43, 173.2, 43, 187.4, 43, 196.26666, 43]
+          size: 24
+          color: red
+          blur-radius: 2
+          font: "VeraBd.ttf"
```

**Comment by Gankro** [comment]
Updated reftest:

```
---
root:
  items:
        - rect: [14, 10, 205, 38]
          color: red
        -
          type: "text-shadow"
          blur-radius: 2
          color: red
          bounds: [14, 10, 205, 38]
        -
          bounds: [14, 18, 205, 35]
          glyphs: [55, 75, 76, 86, 3, 76, 86, 3, 87, 75, 72, 3, 69, 72, 86, 87]
          offsets: [16, 43, 35.533333, 43, 51.533333, 43, 60.4, 43, 72.833336, 43, 80.833336, 43, 89.7, 43, 102.13333, 43, 110.13333, 43, 119, 43, 135, 43, 149.2, 43, 157.2, 43, 173.2, 43, 187.4, 43, 196.26666, 43]
          size: 24
          color: [0,0,0,0]
          font: "VeraBd.ttf"
        -
          type: "pop-text-shadow"
```

Still buggy.
