### ISSUE TITLE
wrench frame saving producing incorrect results

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1402]
If I open this in servo with -Zwr-record

```html
<html>
<body style="background-color: rgb(255,0,0)">
<iframe style="position: fixed; top: 10.5" src="data:text/html,<body style='background-color: rgba(0,0,255,0.5)'>">
</iframe>
</body>
</html>
```

And then replay it in wrench, it renders correctly. However if I tell it to save the results to json/yaml, the results are incorrect and attempting to `show` them produces something different.

There's two problems:

1. the outer document and inner document show up as seperate frames (weird/confusing, but usable)

2. several bounds get changed. For instance the inner document produces this:

```yaml
---
root: 
  items: 
    - 
      bounds: [0, 0, 300, 150]
      clip: [0, 0, 0, 0]
      "clip-and-scroll": 0
      type: "stacking-context"
      "scroll-policy": scrollable
      "transform-style": flat
      items: 
        - 
          bounds: [8, 8, 284, 0]
          clip: [-8947849, -8947849, 17895698, 17895698]
          "clip-and-scroll": 0
          type: rect
          color: 0 0 255 0.5020
  id: [0, 0]
pipelines: []
```

Note that the bounds describe a 284x0 rectangle, where it should actually be 300x150. The 8x8 offset should also presumably be 0x0.
