### ISSUE TITLE
Thin line visible around a transformed primitive

### ISSUE THREAD

**Issue by kvark** [servo/webrender#1797]
See #1732 for the test case image/code.
The used image is attached here:
![1505936895-img-59](https://user-images.githubusercontent.com/107301/31135287-86d25af6-a832-11e7-9694-f5adcf2da4d7.png)

I can repro it on Linux/Intel.

**Comment by Darkspirit** [comment]
This wasn't completely fixed:
The thin grey line can come back if
* I zoom in https://bug1401665.bmoattachments.org/attachment.cgi?id=8910430
* it's rotating https://bug1401665.bmoattachments.org/attachment.cgi?id=8910415

**Comment by kvark** [comment]
@Darkspirit I don't see it in the links you provided. Could you explain your test case a bit more?

**Comment by Darkspirit** [comment]
Comment 5 + video in comment 6
https://bugzilla.mozilla.org/show_bug.cgi?id=1401665#c5

**Comment by Darkspirit** [comment]
There is a new testcase from @mstange in https://bugzilla.mozilla.org/show_bug.cgi?id=1401665#c7 (Thank you!)

**Comment by mstange** [comment]
YAML version of the testcase:

```yaml
---
root: 
  items: 
    - 
      bounds: [0, 0, 0, 0]
      "clip-rect": [0, 0, 0, 0]
      "clip-and-scroll": 0
      "backface-visible": true
      type: "stacking-context"
      "scroll-policy": scrollable
      "transform-style": flat
      items: 
        - 
          bounds: [0, 0, 2880, 1474]
          "clip-rect": [0, 0, 2880, 1474]
          "clip-and-scroll": 0
          "backface-visible": true
          type: rect
          color: white
        - 
          bounds: [0, 0, 2880, 1474]
          "clip-rect": [0, 0, 2880, 1474]
          "clip-and-scroll": 0
          "backface-visible": true
          type: clip
          id: 1
          "content-size": [2880, 1474]
        - 
          "clip-rect": [0, 0, 2880, 1474]
          "clip-and-scroll": 1
          "backface-visible": true
          type: "scroll-frame"
          id: 2
          "content-size": [2880, 1474]
          bounds: [0, 0, 2880, 1474]
        - 
          bounds: [0, 0, 2880, 1474]
          "clip-rect": [0, 0, 2880, 1474]
          "clip-and-scroll": 2
          "backface-visible": true
          type: clip
          id: 3
          "content-size": [2880, 1474]
        - 
          bounds: [0, 0, 2880, 1474]
          "clip-rect": [0, 0, 2880, 1474]
          "clip-and-scroll": 3
          "backface-visible": true
          type: rect
          color: white
        - 
          bounds: [0, 0, 0, 0]
          "clip-rect": [0, 0, 0, 0]
          "clip-and-scroll": 3
          "backface-visible": true
          type: "stacking-context"
          "scroll-policy": scrollable
          transform: [-0.70710677, 0.70710677, 0, 0, -0.70710677, -0.70710677, 0, 0, 0, 0, 1, 0, 441.91882, 235, 0, 1]
          "transform-style": flat
          items: 
            - 
              bounds: [2, 2, 266, 266]
              "clip-rect": [2, 2, 266, 266]
              "clip-and-scroll": 3
              "backface-visible": true
              type: clip
              id: 4
              "content-size": [266, 266]
            - 
              bounds: [2, -243, 202, 288]
              "clip-rect": [2, 0, 202, 45]
              "clip-and-scroll": 4
              "backface-visible": true
              image: "res/1507742000-img-97.png"
              "stretch-size": [202.16667, 287.26666]
              "tile-spacing": [0, 0]
            - 
              bounds: [0, 0, 270, 270]
              "clip-rect": [0, 0, 270, 270]
              "clip-and-scroll": 3
              "backface-visible": true
              type: border
              width: 2
              "border-type": normal
              color: 0 0 255 1.0000
              style: solid
  id: [1, 1]
pipelines: []
```

`res/1507742000-img-97.png` is still the same image as above.
