### ISSUE TITLE
Transformed images with non-transformed clips (and no transformed clip) are not clipped

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1814]
https://bugzilla.mozilla.org/show_bug.cgi?id=1405951

Expected vs actual:
<img width="528" alt="screen shot 2017-10-05 at 2 33 02 pm" src="https://user-images.githubusercontent.com/961291/31246048-3446c89a-a9da-11e7-82c6-ca0ec435e536.png">

In the following YAML testcase, I have a transformed stacking context, and two clips: one clip outside the stacking context (`id: 1`) and one clip inside the stacking context (`id: 2`). The transformed clip `2` has the untransformed clip `1` as its parent clip.

I also have an image inside the transformed stacking context. When I set the image's `clip-and-scroll` to `1`, it is drawn unclipped.
If I set the image's `clip-and-scroll` to `2`, then the image is properly clipped by both `2` and `1`.

```yaml
---
root: 
  items:
    -
      bounds: [16, 16, 404, 404]
      "clip-rect": [16, 16, 404, 404]
      "clip-and-scroll": 0
      "backface-visible": true
      type: border
      width: 2
      "border-type": normal
      color: black
      style: solid
    -
      bounds: [18, 18, 400, 200]
      "clip-rect": [18, 18, 400, 400]
      "clip-and-scroll": 0
      "backface-visible": true
      type: clip
      id: 1
      "content-size": [400, 400]
    -
      bounds: [0, 0, 0, 0]
      "clip-rect": [0, 0, 0, 0]
      "clip-and-scroll": 1
      "backface-visible": true
      type: "stacking-context"
      "scroll-policy": scrollable
      transform: [0.70710677, 0.70710677, 0, 0, -0.70710677, 0.70710677, 0, 0, 0, 0, 1, 0, 218, -64.84271, 0, 1]
      "transform-style": flat
      items:
        -
          bounds: [18, 18, 400, 400]
          "clip-rect": [18, 18, 400, 400]
          "clip-and-scroll": 1
          "backface-visible": true
          type: clip
          id: 2
          "content-size": [400, 400]
        - 
          bounds: [0, 0, 400, 400]
          "clip-rect": [0, 0, 400, 400]
          "clip-and-scroll": 1
          "backface-visible": true
          image: "res/1507226429-img-91.png"
          "stretch-size": [400, 400]
          "tile-spacing": [400, 400]
    - 
      bounds: [0, 0, 0, 0]
      "clip-rect": [0, 0, 0, 0]
      "clip-and-scroll": 0
      "backface-visible": true
  id: [1, 1]
pipelines: []
```

`res/1507226429-img-91.png`: 
![1507226429-img-91](https://user-images.githubusercontent.com/961291/31246292-e3b8312e-a9da-11e7-9869-54d5114a9177.png)
