### ISSUE TITLE
Primitive's bounds are wrong when applying rotate-x.

### ISSUE THREAD

**Issue by mephisto41** [servo/webrender#1856]
See gecko [test case](https://searchfox.org/mozilla-central/source/layout/reftests/transform-3d/transform-style-flat-1a.html)

I created a similar test in yaml
```
---
root:
  items:
    - type: stacking-context
      transform: rotate-x(45)
      items:
        - type: stacking-context
          transform: rotate-x(-45)
          items:
            - type: rect
              bounds: 0 0 100 200
              color: green
```

The rect should be clipped by each stacking context which means the final result should be a green rect in (100, 100) at (0, 0). Current webrender result is a rect in (100, 200) at (0, 0)

@kvark , @glennw , Any thought for this?
