### ISSUE TITLE
Singular transforms cause rendering errors

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1893]
This is the cause of https://bugzilla.mozilla.org/show_bug.cgi?id=1400393 (the chrome sometimes flashing on Mac when you hover tabs).

In this testcase, the rectangles after the stacking context are not rendered:

```yaml
---
root:
  items:
    -
      bounds: [0, 0, 200, 200]
      "clip-rect": [0, 0, 200, 200]
      type: clip
      id: 1
      "content-size": [200, 200]
    # -
    #   bounds: [0, 0, 100, 100]
    #   "clip-rect": [0, 0, 100, 100]
    #   "clip-and-scroll": 1
    #   type: rect
    #   color: yellow
    -
      bounds: [10, 10, 80, 80]
      "clip-and-scroll": 1
      type: "stacking-context"
      transform: [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]
      items:
        -
          bounds: [0, 0, 80, 80]
          "clip-rect": [0, 0, 80, 80]
          "clip-and-scroll": 1
          type: rect
          color: black
    -
      bounds: [0, 100, 100, 100]
      "clip-rect": [0, 100, 100, 100]
      "clip-and-scroll": 1
      type: rect
      color: blue
    -
      bounds: [100, 0, 100, 100]
      "clip-rect": [100, 0, 100, 100]
      "clip-and-scroll": 1
      type: rect
      color: green
    -
      bounds: [100, 100, 100, 100]
      "clip-rect": [100, 100, 100, 100]
      "clip-and-scroll": 1
      type: rect
      color: red
```

If you change the first component of the transform matrix from `0` to `1`, the rectangles return.

Alternatively, if you uncomment the yellow rectangle item, all rectangles suddenly render.
