### ISSUE TITLE
Dotted borders render incorrectly

### ISSUE THREAD

**Issue by nc4rrillo** [servo/webrender#1932]
Hi,
I've noticed dotted borders render the corners seemingly incorrectly.

![](https://i.imgur.com/6x0xBa0.png)

```
---
root: 
  items: 
    - 
      bounds: [5, 5, 490, 490]
      "clip-rect": [5, 5, 490, 490]
      "clip-and-scroll": 0
      "backface-visible": true
      type: border
      width: 25
      "border-type": normal
      color: black
      style: dotted
  id: [0, 0]
pipelines: []
```

**Comment by nc4rrillo** [comment]
Seems related to having a radius < width for the border

```
---
root: 
  items: 
    - 
      bounds: [5, 5, 490, 490]
      "clip-rect": [5, 5, 490, 490]
      "clip-and-scroll": 0
      "backface-visible": true
      type: border
      width: 25
      "border-type": normal
      color: black
      style: dotted
      "radius": 35
  id: [0, 0]
pipelines: []
```

renders as: 


![](https://i.imgur.com/dylVAuL.png)
