### ISSUE TITLE
Image masks don't create an intermediate surface to group the masked contents

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1957]
https://bugzilla.mozilla.org/show_bug.cgi?id=1412375

[Testcase](https://bug1412375.bmoattachments.org/attachment.cgi?id=8922912)

Expected results vs actual results:
<img width="419" alt="screen shot 2017-10-27 at 2 13 04 pm" src="https://user-images.githubusercontent.com/961291/32118795-fdca785e-bb20-11e7-8e4a-e0cd14017982.png">

It might be worth having a different API for grouping masks vs non-grouping clips. For example, a grouping mask could be a property of a stacking context instead of a property of a clip node.

**Comment by mstange** [comment]
> For example, a grouping mask could be a property of a stacking context

It could even be a filter, just like opacity is.

**Comment by glennw** [comment]
This is a timely bug report - as I'm working on optimizing the clip stack bugs / issues in https://github.com/servo/webrender/issues/1817 so I'll try to cover this at the same time, since they are very related.

**Comment by Gankro** [comment]
@glennw in #2443 you said

> R1 failure [2] - I haven't confirmed what is happening in this one, yet. Looking visually, it appears that the image mask is being applied to both the primitive and the resulting stacking context picture. If that is the case, the fix here would be to update Gecko once this lands to supply the image-mask clip chain only to the primitive and/or the stacking context picture, rather than both. As a side-effect of this proposed change, #1957 gets fixed. It may also be related to #2388.

Is this still accurate? Should fixing this bug "just" be a matter of updating gecko now?

**Comment by Gankro** [comment]
Also we don't currently seem to emit a StackingContext in response to a mask; we just PushClip. Are you suggesting we should push an otherwise no-op stacking context and only apply the clip to that, and it will Just Work?

**Comment by Gankro** [comment]
yaml that "should" work (I think):

```yaml
---
root:
  items:
    - type: rect
      bounds: [25, 25, 100, 100]
      color: red
    - type: clip
      bounds: [0, 0, 200, 200]
      id: 0
      image-mask:
          image: "transparent-white.png"
          rect: [0, 0, 200, 200]
          repeat: false
    - type: stacking-context
      bounds: [0, 0, 200, 200]
      clip-and-scroll: 0
      items:
      - type: rect
        bounds: [0, 0, 100, 100]
        color: blue
      - type: rect
        bounds: [50, 50, 100, 100]
        color: green
```

<img width="169" alt="screen shot 2018-03-26 at 5 49 54 pm" src="https://user-images.githubusercontent.com/1136864/37935080-5bb1d872-311e-11e8-8112-69be02e8e257.png">


yaml we're emitting today, but produces an undesirable result (the overlap between the blue and green squares shouldn't have any blue):

```yaml
---
root:
  items:
    - type: rect
      bounds: [25, 25, 100, 100]
      color: red
    - type: clip
      bounds: [0, 0, 200, 200]
      image-mask:
        image: "transparent-white.png"
        rect: [0, 0, 200, 200]
        repeat: false
      items:
      - type: rect
        bounds: [0, 0, 100, 100]
        color: blue
      - type: rect
        bounds: [50, 50, 100, 100]
        color: green
```

<img width="155" alt="screen shot 2018-03-26 at 5 50 25 pm" src="https://user-images.githubusercontent.com/1136864/37935091-605746f0-311e-11e8-8316-ac4c1ee472ee.png">

transparent-white.png:

![transparent-white](https://user-images.githubusercontent.com/1136864/37935116-7011b7ec-311e-11e8-903b-8ab5348f8ed9.png)

**Comment by Gankro** [comment]
Oops made an error with my clipping.

Test That Should Work According To Glenn (opacity(0.999) included to get a Picture in the backend):

```yaml
---
root:
  items:
    - type: rect
      bounds: [25, 25, 100, 100]
      color: red
    - type: clip
      bounds: [0, 0, 200, 200]
      id: 1
      image-mask:
          image: "transparent-white.png"
          rect: [0, 0, 200, 200]
          repeat: false
    - type: stacking-context
      bounds: [0, 0, 200, 200]
      clip-and-scroll: 1
      filters:
        - "opacity(0.999)"
      items:
      - type: rect
        bounds: [0, 0, 100, 100]
        color: blue
      - type: rect
        bounds: [50, 50, 100, 100]
        color: green

```

<img width="153" alt="screen shot 2018-03-26 at 6 01 08 pm" src="https://user-images.githubusercontent.com/1136864/37935494-bf6dcece-311f-11e8-8f71-4c001da6182b.png">


Expected:

```yaml
---
root:
  items:
    - type: rect
      bounds: [25, 25, 100, 100]
      color: red
    
    - type: stacking-context
      bounds: [0, 0, 200, 200]
      filters:
        - "opacity(0.5)"
      items:
      - type: rect
        bounds: [0, 0, 100, 100]
        color: blue
      - type: rect
        bounds: [50, 50, 100, 100]
        color: green
```

<img width="161" alt="screen shot 2018-03-26 at 5 59 31 pm" src="https://user-images.githubusercontent.com/1136864/37935455-92e87a2a-311f-11e8-9d83-eef107e0d0e7.png">


This is actually different from what I'm seeing in gecko (where the mask seems to be ignored completely) but still wrong (no better than clipping the contents individually).
