### ISSUE TITLE
8-12ms GPU with large drop shadow blur radius

### ISSUE THREAD

**Issue by nc4rrillo** [servo/webrender#1986]
On my integrated Intel GPU I'm seeing 8-10ms GPU time while drawing box shadows.
Here's a reduced YAML:

```
---
root: 
  items: 
    - 
      bounds: [0, 0, 550, 400]
      "clip-rect": [0, 0, 550, 400]
      "clip-and-scroll": 0
      "backface-visible": true
      type: rect
      color: 255 255 255 0.9000
    - 
      bounds: [0, 0, 550, 400]
      "clip-rect": [0, 0, 550, 400]
      "clip-and-scroll": 0
      "backface-visible": true
      type: border
      width: [0, 2, 2, 2]
      "border-type": normal
      color: 0 0 0 0.2000
      style: solid
    - 
      bounds: [0, 0, 550, 400]
      "clip-rect": [0, 0, 550, 400]
      "clip-and-scroll": 0
      "backface-visible": true
      type: "box-shadow"
      "box-bounds": [0, 0, 550, 400]
      offset: [0, 2]
      color: 0 0 0 0.2000
      "blur-radius": 4
      "spread-radius": 0
      "clip-mode": outset
    - 
      bounds: [0, 0, 550, 400]
      "clip-rect": [0, 0, 550, 400]
      "clip-and-scroll": 0
      "backface-visible": true
      type: "box-shadow"
      "box-bounds": [0, 0, 550, 400]
      offset: [0, 25]
      color: 0 0 0 0.1000
      "blur-radius": 50
      "spread-radius": 0
      "clip-mode": outset
  id: [0, 0]
pipelines: []
```
![](https://i.imgur.com/K2q1g2X.png)

if I drop the blur radius of the second box shadow to 4, the GPU time goes from 8ms to 3ms.
