### ISSUE TITLE
thread 'RenderBackend' has overflowed its stack after WR update

### ISSUE THREAD

**Issue by nc4rrillo** [servo/webrender#2003]
While upgrading to the latest WR:
```
$ cargo update -p webrender
    Updating git repository `https://github.com/servo/webrender`
    Updating webrender v0.53.1 (https://github.com/servo/webrender#fae962bf) -> #da493fad
    Updating webrender_api v0.53.1 (https://github.com/servo/webrender#fae962bf) -> #da493fad
```
YAML:

```
---
root: 
  items: 
    - 
      bounds: [0, 0, 1024, 768]
      "clip-rect": [0, 0, 1024, 768]
      "clip-and-scroll": 0
      "backface-visible": true
      type: "stacking-context"
      "scroll-policy": scrollable
      transform: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]
      "transform-style": flat
      items: 
        - 
          bounds: [0, 0, 1024, 768]
          "clip-rect": [0, 0, 1024, 768]
          "clip-and-scroll": 0
          "backface-visible": true
          type: rect
          color: 245 245 245 1.0000
        - 
          bounds: [0, 0, 1024, 768]
          "clip-rect": [0, 0, 1024, 768]
          "clip-and-scroll": 0
          "backface-visible": true
          type: border
          width: 0
          "border-type": normal
          color: 0 0 0 0.0000
          style: solid
        - 
          bounds: [0, 0, 1024, 768]
          "clip-rect": [0, 0, 1024, 768]
          "clip-and-scroll": 0
          "backface-visible": true
          type: "stacking-context"
          "scroll-policy": scrollable
          transform: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]
          "transform-style": flat
          items: 
            - 
              "clip-rect": [2, 0, 1020, 766]
              "clip-and-scroll": 0
              "backface-visible": true
              type: "scroll-frame"
              id: 1
              "content-size": [416, 1387]
              bounds: [2, 0, 1020, 766]
            - 
              bounds: [0, 0, 1024, 768]
              "clip-rect": [0, 0, 1024, 768]
              "clip-and-scroll": 0
              "backface-visible": true
              type: rect
              color: 255 255 255 0.0000
            - 
              bounds: [0, 0, 1024, 768]
              "clip-rect": [0, 0, 1024, 768]
              "clip-and-scroll": 0
              "backface-visible": true
              type: border
              width: [0, 2, 2, 2]
              "border-type": normal
              color: 0 0 0 0.2000
              style: solid
            - 
              bounds: [0, 0, 1020, 1387]
              "clip-rect": [0, 0, 1020, 1387]
              "clip-and-scroll": 1
              "backface-visible": true
              type: "stacking-context"
              "scroll-policy": scrollable
              transform: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 2, 0, 0, 1]
              "transform-style": flat
              items: 
                - 
                  bounds: [0, 0, 1020, 1387]
                  "clip-rect": [0, 0, 1020, 1387]
                  "clip-and-scroll": 1
                  "backface-visible": true
                  type: rect
                  color: 255 255 255 0.0000
                - 
                  bounds: [0, 0, 1020, 1387]
                  "clip-rect": [0, 0, 1020, 1387]
                  "clip-and-scroll": 1
                  "backface-visible": true
                  type: border
                  width: 0
                  "border-type": normal
                  color: 0 0 0 0.0000
                  style: solid
                - 
                  bounds: [0, 0, 1000, 23]
                  "clip-rect": [0, 0, 1000, 23]
                  "clip-and-scroll": 1
                  "backface-visible": true
                  type: "stacking-context"
                  "scroll-policy": scrollable
                  transform: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 10, 10, 0, 1]
                  "transform-style": flat
                  items: 
                    - 
                      bounds: [0, 0, 1000, 23]
                      "clip-rect": [0, 0, 1000, 23]
                      "clip-and-scroll": 1
                      "backface-visible": true
                      type: rect
                      color: 255 255 255 0.0000
                    - 
                      bounds: [0, 0, 1000, 23]
                      "clip-rect": [0, 0, 1000, 23]
                      "clip-and-scroll": 1
                      "backface-visible": true
                      type: border
                      width: 0
                      "border-type": normal
                      color: 0 0 0 0.0000
                      style: solid
                    - 
                      bounds: [0, 0, 1000, 23]
                      "clip-rect": [0, 0, 1000, 23]
                      "clip-and-scroll": 1
                      "backface-visible": true
                      glyphs: [54, 82, 79, 76, 71]
                      offsets: [0, 22, 19, 22, 37, 22, 45, 22, 53, 22]
                      size: 22.5
                      color: black
                      font: "res/1510024500-font-1.ttf"
                - 
                  bounds: [0, 0, 400, 400]
                  "clip-rect": [0, 0, 400, 400]
                  "clip-and-scroll": 1
                  "backface-visible": true
                  type: "stacking-context"
                  "scroll-policy": scrollable
                  transform: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 10, 53, 0, 1]
                  "transform-style": flat
                  items: 
                    - 
                      bounds: [0, 0, 400, 400]
                      "clip-rect": [0, 0, 400, 400]
                      "clip-and-scroll": 1
                      "backface-visible": true
                      type: rect
                      color: 76.5 0 0 1.0000
                    - 
                      bounds: [0, 0, 400, 400]
                      "clip-rect": [0, 0, 400, 400]
                      "clip-and-scroll": 1
                      "backface-visible": true
                      type: border
                      width: [15, 25, 15, 25]
                      "border-type": normal
                      color: 0 178.5 0 1.0000
                      style: solid
                - 
                  bounds: [0, 0, 1000, 23]
                  "clip-rect": [0, 0, 1000, 23]
                  "clip-and-scroll": 1
                  "backface-visible": true
                  type: "stacking-context"
                  "scroll-policy": scrollable
                  transform: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 10, 473, 0, 1]
                  "transform-style": flat
                  items: 
                    - 
                      bounds: [0, 0, 1000, 23]
                      "clip-rect": [0, 0, 1000, 23]
                      "clip-and-scroll": 1
                      "backface-visible": true
                      type: rect
                      color: 255 255 255 0.0000
                    - 
                      bounds: [0, 0, 1000, 23]
                      "clip-rect": [0, 0, 1000, 23]
                      "clip-and-scroll": 1
                      "backface-visible": true
                      type: border
                      width: 0
                      "border-type": normal
                      color: 0 0 0 0.0000
                      style: solid
                    - 
                      bounds: [0, 0, 1000, 23]
                      "clip-rect": [0, 0, 1000, 23]
                      "clip-and-scroll": 1
                      "backface-visible": true
                      glyphs: [39, 68, 86, 75, 72, 71]
                      offsets: [0, 22, 23, 22, 41, 22, 57, 22, 76, 22, 94, 22]
                      size: 22.5
                      color: black
                      font: "res/1510024500-font-1.ttf"
                - 
                  bounds: [0, 0, 400, 400]
                  "clip-rect": [0, 0, 400, 400]
                  "clip-and-scroll": 1
                  "backface-visible": true
                  type: "stacking-context"
                  "scroll-policy": scrollable
                  transform: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 10, 516, 0, 1]
                  "transform-style": flat
                  items: 
                    - 
                      bounds: [0, 0, 400, 400]
                      "clip-rect": [0, 0, 400, 400]
                      "clip-and-scroll": 1
                      "backface-visible": true
                      type: rect
                      color: 0 76.5 0 1.0000
                    - 
                      bounds: [0, 0, 400, 400]
                      "clip-rect": [0, 0, 400, 400]
                      "clip-and-scroll": 1
                      "backface-visible": true
                      type: border
                      width: [15, 25, 15, 25]
                      "border-type": normal
                      color: 0 178.5 0 1.0000
                      style: dashed
                - 
                  bounds: [0, 0, 1000, 23]
                  "clip-rect": [0, 0, 1000, 23]
                  "clip-and-scroll": 1
                  "backface-visible": true
                  type: "stacking-context"
                  "scroll-policy": scrollable
                  transform: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 10, 936, 0, 1]
                  "transform-style": flat
                  items: 
                    - 
                      bounds: [0, 0, 1000, 23]
                      "clip-rect": [0, 0, 1000, 23]
                      "clip-and-scroll": 1
                      "backface-visible": true
                      type: rect
                      color: 255 255 255 0.0000
                    - 
                      bounds: [0, 0, 1000, 23]
                      "clip-rect": [0, 0, 1000, 23]
                      "clip-and-scroll": 1
                      "backface-visible": true
                      type: border
                      width: 0
                      "border-type": normal
                      color: 0 0 0 0.0000
                      style: solid
                    - 
                      bounds: [0, 0, 1000, 23]
                      "clip-rect": [0, 0, 1000, 23]
                      "clip-and-scroll": 1
                      "backface-visible": true
                      glyphs: [39, 82, 87, 87, 72, 71]
                      offsets: [0, 22, 23, 22, 41, 22, 53, 22, 65, 22, 83, 22]
                      size: 22.5
                      color: black
                      font: "res/1510024500-font-1.ttf"
                - 
                  bounds: [0, 0, 400, 400]
                  "clip-rect": [0, 0, 400, 400]
                  "clip-and-scroll": 1
                  "backface-visible": true
                  type: "stacking-context"
                  "scroll-policy": scrollable
                  transform: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 10, 979, 0, 1]
                  "transform-style": flat
                  items: 
                    - 
                      bounds: [0, 0, 400, 400]
                      "clip-rect": [0, 0, 400, 400]
                      "clip-and-scroll": 1
                      "backface-visible": true
                      type: clip
                      id: 2
                      "content-size": [400, 400]
                      complex: 
                        - 
                          rect: [0, 0, 400, 400]
                          radius: [25, 25]
                          "clip-mode": clip
                    - 
                      bounds: [0, 0, 400, 400]
                      "clip-rect": [0, 0, 400, 400]
                      "clip-and-scroll": 2
                      "backface-visible": true
                      type: rect
                      color: 0 0 76.5 1.0000
                    - 
                      bounds: [0, 0, 400, 400]
                      "clip-rect": [0, 0, 400, 400]
                      "clip-and-scroll": 2
                      "backface-visible": true
                      type: border
                      width: [15, 25, 15, 25]
                      "border-type": normal
                      color: 
                        - 0 178.5 76.5 1.0000
                        - 178.5 76.5 0 1.0000
                        - 153 178.5 76.5 1.0000
                        - 76.5 178.5 0 1.0000
                      style: dotted
                      radius: [25, 25]
  id: [0, 0]
pipelines: []
```
If it helps any, it only happens if I scroll a few times. 

STR:
1. `git checkout https://github.com/nc4rrillo/indigo`
2. `cd indigo/indigo`
3. `cargo update -p webrender`
4. `cargo run --example borders`
5. Scroll up and down a few times.
