### ISSUE TITLE
Overlapping opposite rounded corners have drawing errors

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2174]
https://bugzilla.mozilla.org/show_bug.cgi?id=1423603

[Testcase](https://bug1423603.bmoattachments.org/attachment.cgi?id=8935002)

Actual vs expected results:
<img width="473" alt="screen shot 2017-12-06 at 10 15 29 am" src="https://user-images.githubusercontent.com/961291/33668679-6f8cb1d4-da6e-11e7-8073-3699c4d117da.png">

```yaml
---
root:
  items:
    - type: stacking-context
      bounds: [0, 0, 1000, 1000]
      items:
        - type: clip
          bounds: [ 0, 0, 200, 200 ]
          complex:
            - rect: [ 0, 0, 200, 200 ]
              radius:
                top-left: [180, 180]
                top-right: [0, 0]
                bottom-left: [0, 0]
                bottom-right: [180, 180]
          items:
            - type: rect
              bounds: [ 0, 0, 200, 200 ]
              color: blue
```
