### ISSUE TITLE
Box-shadows with blur render incorrectly if there are opposite rounded corners whose bounding boxes overlap

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2179]
https://bugzilla.mozilla.org/show_bug.cgi?id=1423683

[Testcase](https://bug1423683.bmoattachments.org/attachment.cgi?id=8935073)

Actual vs expected results:
<img width="707" alt="screen shot 2017-12-06 at 1 59 59 pm" src="https://user-images.githubusercontent.com/961291/33679899-ff6bfde0-da8d-11e7-9154-f8209156f9c8.png">

```yaml
---
root:
  items:
    - type: stacking-context
      bounds: [0, 0, 1000, 1000]
      items:
        - type: box-shadow
          bounds: [ 0, 0, 200, 200 ]
          color: red
          clip-mode: outset
          offset: 200 0
          blur-radius: 1
          spread-radius: 0
          border-radius:
            top-left: [100, 100]
            top-right: [0, 0]
            bottom-left: [0, 0]
            bottom-right: [150, 150]
```
