### ISSUE TITLE
Incorrect box-shadow rendering when the blur of adjacent rounded corners overlaps

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2180]
https://bugzilla.mozilla.org/show_bug.cgi?id=1423692

[Testcase](https://bug1423692.bmoattachments.org/attachment.cgi?id=8935086)

Actual vs expected results:
<img width="522" alt="screen shot 2017-12-06 at 2 23 46 pm" src="https://user-images.githubusercontent.com/961291/33681054-70ed3f26-da91-11e7-893e-c4d0cb3dfc77.png">

```yaml
---
root:
  items:
    - type: stacking-context
      bounds: [0, 0, 1000, 1000]
      items:
        - type: box-shadow
          bounds: [ 50, 10, 200, 80 ]
          color: black
          clip-mode: outset
          offset: 0 150
          blur-radius: 20
          border-radius:
            top-left: [100, 40]
            top-right: [0, 0]
            bottom-left: [100, 40]
            bottom-right: [0, 0]
```
