### ISSUE TITLE
Inset box-shadows render incorrectly in some cases

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2182]
https://bugzilla.mozilla.org/show_bug.cgi?id=1423696

[Testcase](https://bug1423696.bmoattachments.org/attachment.cgi?id=8935091)

Actual vs expected results:
<img width="490" alt="screen shot 2017-12-06 at 2 34 15 pm" src="https://user-images.githubusercontent.com/961291/33681744-7bc3bef0-da93-11e7-8188-72d194b0a2ba.png">

It looks like the element's shape also clips the pre-blur shadow shape, instead of just clipping the blurred result.

```yaml
---
root:
  items:
    - type: stacking-context
      bounds: [0, 0, 1000, 1000]
      items:
        - type: box-shadow
          bounds: [ 22, 22, 200, 80 ]
          color: blue
          clip-mode: inset
          offset: -2 -2
          blur-radius: 20
          spread-radius: 0
          border-radius:
            top-left: [0, 0]
            top-right: [0, 0]
            bottom-left: [0, 0]
            bottom-right: [0, 0]
```
