### ISSUE TITLE
Border rendering glitches

### ISSUE THREAD

**Issue by nc4rrillo** [servo/webrender#2183]
Bad (taken from wrench with dbg alpha primitives / render target on):
![](https://i.imgur.com/uvUh0zG.png)

Good (taken from a jsfiddle I made [here](https://jsfiddle.net/LLg2arf9/)):
![](https://i.imgur.com/pyjBvtm.png)

```
---
root: 
  items: 
    - 
      bounds: [0, 0, 1024, 768]
      "clip-rect": [0, 0, 1024, 768]
      "clip-and-scroll": 0
      "backface-visible": true
      type: "stacking-context"
      "scroll-policy": scrollable
      "transform-style": flat
      filters: []
      items: 
        - 
          bounds: [0, 0, 200, 200]
          "clip-rect": [0, 0, 200, 200]
          "clip-and-scroll": 0
          "backface-visible": true
          type: border
          width: 10
          "border-type": normal
          color: red
          style: dashed
          radius: [180, 180]
        - 
          bounds: [200, 0, 380, 380]
          "clip-rect": [200, 0, 380, 380]
          "clip-and-scroll": 0
          "backface-visible": true
          type: border
          width: 10
          "border-type": normal
          color: green
          style: dashed
          radius: [180, 180]
        - 
          bounds: [580, 0, 200, 200]
          "clip-rect": [580, 0, 200, 200]
          "clip-and-scroll": 0
          "backface-visible": true
          type: border
          width: 10
          "border-type": normal
          color: red  
          style: solid
          radius: [180, 180]
        - 
          bounds: [780, 0, 380, 380]
          "clip-rect": [780, 0, 380, 380]
          "clip-and-scroll": 0
          "backface-visible": true
          type: border
          width: 10
          "border-type": normal
          color: green
          style: solid
          radius: [180, 180]
        - 
          bounds: [0, 380, 200, 200]
          "clip-rect": [0, 380, 200, 200]
          "clip-and-scroll": 0
          "backface-visible": true
          type: border
          width: 10
          "border-type": normal
          color: red
          style: dotted
          radius: [180, 180]
        - 
          bounds: [200, 380, 380, 380]
          "clip-rect": [200, 380, 380, 380]
          "clip-and-scroll": 0
          "backface-visible": true
          type: border
          width: 10
          "border-type": normal
          color: green
          style: dotted
          radius: [180, 180]
  id: [0, 0]
pipelines: []
```

From what I can tell it hasto do with how the bounds of the border relate to the border radius. You'll notice in the green examples the only difference is the bounds are bigger.
