### ISSUE TITLE
drop-shadow render incorrectly if the shadow close to the edge of viewport.

### ISSUE THREAD

**Issue by mephisto41** [servo/webrender#2197]
testcase

```
---
root:
  items:
    - type: stacking-context
      bounds: [10, 10, 400, 400]
      filters: drop-shadow([0, 0], 20, [255, 0, 0, 1])
      items:
      - type: rect
        bounds: 0 0 256 256
        color: green
```
