### ISSUE TITLE
regression: Animation rendered all over the place with webrender

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2272]
Filing for https://bugzilla.mozilla.org/show_bug.cgi?id=1420754

This was determined to be a regression from #2069 but was not fixed by the fixes for #2133.

**Comment by glennw** [comment]
I can see the cause of this. In the test case provided, the vertices end up with a negative W coordinate, and therefore the code that calculates the screen bounding box of the primitive is incorrect. This results in a render task being allocated where the size is too small for the actual primitive that gets rendered.

**Comment by glennw** [comment]
Minimal test case:

```
---
root:
  items:
    -
      bounds: [0, 0, 1000, 1000]
      type: "stacking-context"
      transform-style: preserve-3d
      perspective: 300
      items:
        -
          bounds: [0, 0, 1000, 1000]
          type: "stacking-context"
          transform: rotate-x(70)
          items:
            -
              bounds: [300, 200, 400, 4000]
              image: checkerboard(2, 16, 12)
```

As soon as we have a primitive that extends beyond the near plane, this causes issues with screen bounding rect calculation, and also some kind of issue in the plane splitting and/or split composite code. This is only a problem if the div in question is rendered to an off-screen surface (i.e. preserve-3d or opacity etc).
