### ISSUE TITLE
regression: Specific wikipedia page: Semi-donut chart shows lines on the bottom half where there shouldn't be

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2294]
Filing for the "first regression" reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1430063 where the chart goes from looking correct to having streaky lines in the bottom half.

Narrowed down the WR regression range to this:
```
* c16b37dd Auto merge of #2228 - glennw:overlap-border, r=kvark
* e3d7353a Fix overlapping border radii handling.
```

So definitely from #2228.

**Comment by glennw** [comment]
I did some investigation of this - that bisect is not quite correct. It occurred in https://github.com/servo/webrender/pull/2242 which merged just after that.

I can see what the problem is, but I'm not sure of the correct fix. @mrobinson could you take a look at this?

A reduced test case:

```
---
root:
  items:
      -
        type: "stacking-context"
        items:
          -
            bounds: [1488, 111, 356, 197]
            "clip-rect": [1488, 111, 356, 197]
            type: clip
            id: 5
            "content-size": [356, 197]
          -
            "clip-and-scroll": 5
            type: "stacking-context"
            transform: [0.98883086, 0.14904226, 0, 0, -0.14904226, 0.98883086, 0, 0, 0, 0, 1, 0, 1533.3134, 109.21605, 0, 1]
            items:
              -
                "clip-and-scroll": 5
                type: "stacking-context"
                transform: [0.7818315, 0.6234898, 0, 0, -0.6234898, 0.7818315, 0, 0, 0, 0, 1, 0, 132.98201, -64.04077, 0, 1]
                items:
                  -
                    "clip-and-scroll": 5
                    type: "stacking-context"
                    transform: [0.93087375, 0.36534107, 0, 0, -0.36534107, 0.93087375, 0, 0, 0, 0, 1, 0, 68.64584, -46.80194, 0, 1]
                    items:
                      -
                        "clip-and-scroll": 5
                        type: "stacking-context"
                        transform: [0.8262389, 0.56332004, 0, 0, -0.56332004, 0.8262389, 0, 0, 0, 0, 1, 0, 116.458824, -61.550323, 0, 1]
                        items:
                          -
                            "clip-and-scroll": 5
                            type: "stacking-context"
                            transform: [0.90096885, 0.43388373, 0, 0, -0.43388373, 0.90096885, 0, 0, 0, 0, 1, 0, 84.200554, -52.906708, 0, 1]
                            items:
                              -
                                "clip-and-scroll": 5
                                type: "stacking-context"
                                transform: [0.98883086, 0.14904226, 0, 0, -0.14904226, 0.98883086, 0, 0, 0, 0, 1, 0, 25.3134, -21.78395, 0, 1]
                                items:
                                  -
                                    "clip-and-scroll": 5
                                    type: "stacking-context"
                                    transform: [0.73305184, 0.68017274, 0, 0, -0.68017274, 0.73305184, 0, 0, 0, 0, 1, 0, 149.64511, -65.28949, 0, 1]
                                    items:
                                      -
                                        bounds: [0, 0, 316, 158]
                                        "clip-rect": [0, 0, 316, 158]
                                        "clip-and-scroll": 5
                                        type: rect
                                        color: red
```

After that PR, this displays as a fairly large rectangle. Before that PR, this will correctly have a clip mask applied and show as a very thin rectangle.

With current master it doesn't get any clip mask applied at all. What happens is that the code here https://github.com/servo/webrender/blob/c8babed1402ee71a208fcbea74a11b2c0a5e8843/webrender/src/prim_store.rs#L1984 drops the clip source in question. It says that this clip source is irrelevant, because the clip chain outer result intersected with the prim rect is completely inside the inner rect of that clip.

But since they are incompatible coordinate systems, there's no local clip rect that applies in the vertex shader, and since this clip gets filtered out, there is no clip mask generated either.

Thoughts @mrobinson  ?
