### ISSUE TITLE
regression: embedded rotate transform inside perspective style produces incorrect Z order

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2337]
Filing for bug https://bugzilla.mozilla.org/show_bug.cgi?id=1432665 which has a reduced test case attached to the bug. This is a regression from #2031

**Comment by glennw** [comment]
I can see the cause of this - I'll work on fixing this next week. Note to self - when we run the polygon split, we don't order the resulting polygons correct with regard to the un-transformed items in the parent stacking context.

**Comment by glennw** [comment]
Reduced test case:

```
---
root:
  items:
    -
      type: "stacking-context"
      transform: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 15, 15, 0, 1]
      "transform-style": "preserve-3d"
      perspective: [1, 0, 0, 0, 0, 1, 0, 0, -0.05, -0.1, 1, -0.00066666666, 0, 0, 0, 1]
      items:
        -
          bounds: [0, 0, 150, 300]
          type: rect
          color: 255 0 0 1.0000
    -
      bounds: [203, 15, 150, 300]
      type: rect
      color: 255 0 0 1.0000
    -
      bounds: [0, 0, 450, 150]
      type: rect
      color: 0 0 0 0.6667

```
