### ISSUE TITLE
regression: Improper rendering of filter:drop-shadow() when using WebRender

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2374]
https://bugzilla.mozilla.org/show_bug.cgi?id=1434801

Testcase is https://bug1434801.bmoattachments.org/attachment.cgi?id=8947337

Regression range is:

```
* 68dcbc46 Auto merge of #2243 - mephisto41:drop-shadow-edge, r=kvark
* f0cf25ef Fix drop-shadow render incorrectly on viewport's edge.
```

**Comment by glennw** [comment]
Minimal test case:

```
---
root:
  items:
    -
      type: "stacking-context"
      items:
        -
          bounds: [0, 111, 1920, 1450]
          "clip-rect": [0, 111, 1920, 1450]
          type: iframe
          id: [1, 2]
pipelines:
  -
    id: [1, 2]
    items:
      -
        type: "stacking-context"
        items:
          -
            type: "stacking-context"
            filters:
              - "drop-shadow([1.5,1.5],0,[0,0,0,255])"
            items:
              -
                bounds: [12, 12, 1485, 987]
                "clip-rect": [12, 12, 1485, 987]
                image: "res/1517888277-img-28.png"
```

Looks like there is a double offset being applied somewhere, investigating.
