### ISSUE TITLE
fast text-shadows of non-black text have unreasonably incorrect subpixels

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#2384]
I suspect this is the result of the gamma fudging @lsalzman and I agreed on. I don't think we can ship this.

```yaml
---
root:
  items:
        -
          type: "shadow"
          bounds: [10, 14, 220, 200]
          blur-radius: 0
          offset: [0, 20]
          color: black
        -
          text: "wow this is really wrong"
          origin: [10, 44]
          size: 18
          color: red
          font: "VeraBd.ttf"
        -
          type: "pop-all-shadows"
```

![screen shot 2018-02-06 at 11 21 46 am](https://user-images.githubusercontent.com/1136864/35870569-fa295c92-0b2f-11e8-8861-6275406c637a.png)
