### ISSUE TITLE
Clip masks + snapping

### ISSUE THREAD

**Issue by glennw** [servo/webrender#2501]
When primitives are drawn, we snap them to the nearest device pixel. However, we don't do the same with clip masks.

Consider the following reftest:

```
---
root:
  items:
    - type: clip
      bounds: [0, 0, 1000, 1000]
      complex:
        - rect: [50.3, 50.3, 100, 100]
          radius: 16
      items:
      - type: rect
        bounds: 50.3 50.3 100 100
        color: red

    - type: rect
      bounds: 200.3 50.3 100 100
      color: green
```

And the reference:

```
---
root:
  items:
    - type: clip
      bounds: [0, 0, 1000, 1000]
      complex:
        - rect: [50, 50, 100, 100]
          radius: 16
      items:
      - type: rect
        bounds: 50 50 100 100
        color: red

    - type: rect
      bounds: 200 50 100 100
      color: green
```

In this case, the green rect is exactly the same in both cases, because the ```0.3``` gets snapped to a device pixel. However, the red rect is different - the primitive gets snapped to a device pixel, but the clip mask doesn't.

![diff](https://user-images.githubusercontent.com/2350882/37192615-70bbe028-235e-11e8-8479-5dd4926fe0f2.png)
