### ISSUE TITLE
local clip-rects in text shadows just squish the glyphs

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#2549]
Was looking at turning on partial ligature handling, but it seems there's still some bugs.

```
data:text/html,<head><meta charset="utf8"></head><div style="font-size:30px;text-shadow: 400px 0px 1px blue;"><span style="color:red;">%E0%A4%AA%E0%A4%A8</span>%E0%A5%8D%E0%A4%B9 <span style="color:red">%E0%A4%AA%E0%A4%A8%E0%A5%8D</span>%E0%A4%B9 <span style="color:red">%E0%A4%A4</span>%E0%A5%8D%E0%A4%B0 <span style="color:red">%E0%A4%B0%E0%A5%8D</span>%E0%A4%9A<span style="color:red">%E0%A4%95</span>%E0%A5%83%E0%A4%95<span style="color:red">%E0%A5%83</span> <span style="color:red">%E0%A4%A1</span><span style="color:green">%E0%A5%8D%E0%A4%A1</span><span style="color:red">%E0%A4%A8</span><span style="color:green">%E0%A5%8D%E0%A4%B9</span><span style="color:blue">%E0%A5%83</span><span style="color:orange">%E0%A5%87</span>  <span style="color:red">%D9%84</span><span style="color:green">%D8%A7</span><span style="color:red">%D8%A8</span><span style="color:green">%D8%B3</span><span style="color:blue">%D9%85</span>  <span style="color:red">%D8%A7</span><span style="color:green">%D9%84</span><span style="color:blue">%D9%84</span><span style="color:orange">%D9%87</span></div>
```

Firefox:
<img width="771" alt="screen shot 2018-03-20 at 3 02 07 pm" src="https://user-images.githubusercontent.com/1136864/37677077-4a06dc08-2c50-11e8-9a6d-8b58baa75c86.png">

Webrenderfox+my patch that lets clips get fed down:
<img width="767" alt="screen shot 2018-03-20 at 3 05 00 pm" src="https://user-images.githubusercontent.com/1136864/37677086-4e8cef4c-2c50-11e8-8c69-ad3fea54b819.png">

Notice that several of the glyphs in the shadow show up multiple times squished to a thin box, when what's being requested is that they each be drawn with normal scale but clipped to that thin box (creating the illusion of a single glyph).

Filling this so I don't forget, will make a reftest for this in a bit.

**Comment by Gankro** [comment]
<img width="97" alt="screen shot 2018-03-20 at 4 39 18 pm" src="https://user-images.githubusercontent.com/1136864/37681512-49843c5a-2c5d-11e8-889e-cdfca3beefd2.png">

```yaml
---
root:
  items:
        -
          type: "shadow"
          blur-radius: 2
          bounds: [14, 18, 205, 35]
          offset: [40, 0]
          color: black
        -
          bounds: [14, 18, 205, 35]
          clip-rect: [16, 18, 14, 14]
          glyphs: [58]
          offsets: [16, 43]
          size: 18
          color: [255, 0, 0, 1]
          font: "VeraBd.ttf"
        -
          bounds: [14, 18, 205, 35]
          clip-rect: [30, 18, 14, 14]
          glyphs: [58]
          offsets: [16, 43]
          size: 18
          color: [0, 255, 0, 1]
          font: "VeraBd.ttf"
        -
          bounds: [14, 18, 205, 35]
          clip-rect: [16, 32, 14, 14]
          glyphs: [58]
          offsets: [16, 43]
          size: 18
          color: [0, 0, 255, 1]
          font: "VeraBd.ttf"
        -
          bounds: [14, 18, 205, 35]
          clip-rect: [30, 32, 14, 14]
          glyphs: [58]
          offsets: [16, 43]
          size: 18
          color: [255, 0, 255, 1]
          font: "VeraBd.ttf"
        -
          type: "pop-all-shadows"
```
