### ISSUE TITLE
Tiled gradients with many tiles can render incorrectly

### ISSUE THREAD

**Issue by eqrion** [servo/webrender#2560]
Discovered from looking at the test case attached to [bug 1443912](https://bugzilla.mozilla.org/show_bug.cgi?id=1443912).

The following test case is a red rect covered entirely by a 100x100 tile tiled radial gradient. Each tile of the radial gradient is solid blue, so we should only see a blue rect on the screen.

Instead we see that some limit on tiles is being reached and not all tiles are being drawn.

```yaml
---
root:
  items:
    - type: rect
      bounds: 0 0 800 800
      color: red

    - type: radial-gradient
      bounds: 0 0 800 800
      center: 4 4
      radius: 4 4
      stops: [0, blue, 1, blue]
      tile-size: 8 8
      tile-spacing: 0 0
```

![many-tiles](https://user-images.githubusercontent.com/4984292/37789255-66da39b0-2dd1-11e8-82eb-c15a919ff9d1.png)

cc @jrmuizel
