### ISSUE TITLE
Incorrect rendering in some cases with new AA method.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#2576]
In some cases, the new AA method from https://github.com/servo/webrender/pull/2445 is producing incorrect rendering.

For example, compare these two images:

![bad](https://user-images.githubusercontent.com/2350882/37951481-0e95ee52-318c-11e8-8edb-1e3b5be50a63.png)
![good](https://user-images.githubusercontent.com/2350882/37951482-0ed16022-318c-11e8-8802-af0194d122bd.png)

The first image is using the new technique - the values in the center of the clip mask are 243 / 255, which is why they are considered partially transparent and (incorrectly) blend with the box shadow below.

I locally reverted #2445 to generate the second image - in this case, it produces an opaque clip region in the center of the primitive, so it draws correctly without any translucency.

These images were generated from loading the following test case in wrench:

```
---
root:
  items:
    - type: stacking-context
      transform: rotate-z(45) rotate-x(60)
      transform-origin: 300 300
      items:
        - type: box-shadow
          bounds: [0, 0, 80, 80]
          color: [100, 100, 100]
          offset: [30, 30]
          border-radius: 8

        - type: clip
          bounds: [0, 0, 80, 80]
          complex:
            - rect: [0, 0, 80, 80]
              radius: 8
          items:
            - type: rect
              color: [100, 150, 200]
              bounds: [0, 0, 80, 80]

        - type: clip
          bounds: [90, 0, 80, 80]
          complex:
            - rect: [90, 0, 80, 80]
              radius: 8
          items:
          - type: rect
            color: [100, 150, 200]
            border-radius: 8
            bounds: [90, 0, 80, 80]
```
