### ISSUE TITLE
Terrible performance on giant dotted and dashed border corners

### ISSUE THREAD

**Issue by mrobinson** [servo/webrender#2712]
When dotted and dashed border corners use very, very shallow angles, they create hundreds or thousands of dots and dashes. This leads to very bad performance. We should work to improve this situation. Some examples of web content that produces this issue are:
```html
<span style="border-radius:50%;border:dashed;display:inline-block;width:115001px">xxx</span>
```

```html
<span style="border-radius:50%;border:dotted;display:inline-block;width:115001px">xxx</span>
```

Wrench yaml that demonstrates this is:
```yaml
---
root:
  items:
    -
      bounds: [0, 0, 1000, 1000]
      type: "stacking-context"
      items:
       -
         bounds: [16, 16, 115001, 50]
         "clip-rect": [16, 16, 115001, 50]
         type: border
         width: 20
         "border-type": normal
         color: black
         style: dashed
         radius: [57500, 25]
```

```yaml
---
root:
  items:
    -
      bounds: [0, 0, 1000, 1000]
      type: "stacking-context"
      items:
       -
         bounds: [16, 16, 115001, 50]
         "clip-rect": [16, 16, 115001, 50]
         type: border
         width: 20
         "border-type": normal
         color: black
         style: dotted
         radius: [57500, 25]
```
