### ISSUE TITLE
Blur filter not clipped properly

### ISSUE THREAD

**Issue by Pryx** [servo/webrender#2934]
I've been noticing for some time weird blur under Facebook videos when running Firefox with Webrender. I've been able to track down the issue and create a minimal testcase:
```
<!DOCTYPE html>
<html>
<head>
	<title>Test</title>
</head>
<body>
	<div style="height:200px;width:200px;overflow:hidden">
		<img src="http://via.placeholder.com/200x200" style="filter:blur(20px)">
	</div>
</body>
</html>
```

Side by side comparison with Opera: 
![side by side](https://user-images.githubusercontent.com/5222912/43343885-2f96c768-91e8-11e8-985f-03fcec2b7128.PNG)

**Comment by nical** [comment]
We create a statcking context which refers to the correct clip chain and has a blur filter applied to it, however the clip attached to the stacking context is applied to the content of the stacking context before the blur is applied.
@glennw is this the correct semantic of the stacking context clip? if so I guess we should wrap it in another stacking context that has the clip and probably make it so that the blur's stacking context doesn't get the clip attached.

My guess is that the intent was for the clip to be applied to the stacking context (rather than the source of its filter) but since it doesn't matter for most filters we need to handle blurs differently. We don't seem to have any code attempting to apply clips to a picture primitive though.

**Comment by nical** [comment]
Equivalent yaml testcase:

```
---
root:
  items:
    - type: stacking-context
      bounds: [100, 100, 300, 300]
      filters: blur(10)
      complex-clip:
        rect: [200, 200, 100, 100]
      items:
      - image: "reftests/filters/firefox.png"
        bounds: 20 20 256 256
```
