### ISSUE TITLE
Iframe breaks out of its boundaries

### ISSUE THREAD

**Issue by Darkspirit** [servo/webrender#3146]
[bug 1495305](https://bugzilla.mozilla.org/show_bug.cgi?id=1495305)
[Screencast](https://bugzilla.mozilla.org/attachment.cgi?id=9013159)
URL: https://material.io/tools/resizer/
Probably regressed by #3046.

**Comment by gw3583** [comment]
Minimal repro case:

```
root:
  items:
    - type: stacking-context
      transform: scale(0.5)
      items:
        - type: rect
          color: green
          bounds: [100, 100, 100, 100]
        - type: scroll-frame
          bounds: [100, 100, 100, 100]
          content-size: [260, 260]
          scroll-offset: [0, 50]
          items:
            - image: checkerboard(2, 16, 16)
              bounds: [100, 100, 260, 260]
              hit-testing-tag: [0, 0]
```
