### ISSUE TITLE
Inset box shadow with non-round blur radius plus non-round scale transform renders unevenly

### ISSUE THREAD

**Issue by cpearce** [servo/webrender#3151]
This YAML test case:
```yaml
---
root:
  items:
        - type: stacking-context
          bounds: [0, 0, 1000, 1000]
          transform: scale(0.77)
          items:
            - type: box-shadow
              bounds: [ 200, 50, 100, 100 ]
              color: black
              clip-mode: inset
              blur-radius: 3.75
              border-radius: [ 0, 0, 0, 0 ]
```

It renders with its right hand side darker thank it's left hand side:
[https://pearce.org.nz/wr-box-shadow.png](https://pearce.org.nz/wr-box-shadow.png)

I suspect it's got something to do with the non-round blur radius and non-round scale transform.

This is causing Gecko's [boxshadow-large-border-radius.html](https://searchfox.org/mozilla-central/rev/819cd31a93fd50b7167979607371878c4d6f18e8/layout/reftests/box-shadow/boxshadow-large-border-radius.html) reftest to fail with WebRender enabled.
