### ISSUE TITLE
Items are optimized out even if they cast a shadow that would be visible

### ISSUE THREAD

**Issue by nical** [servo/webrender#3266]
In the following test case the rect is off screen but it casts a shadow that should be visible. We currently don't display the shadow for this item but I believe we should (Gecko relies on it).

```yaml
---
root:
  items:
    - type: stacking-context
      bounds: [-100, -100, 400, 400]
      filters: drop-shadow([0, 50], 0, [255, 0, 0, 1])
      items:
      - type: rect
        bounds: 0 -100 100 100
        color: green
```

If the y offset of the rect is moved, say, from `-100` to `-99` so that a row of pixels of the rect becomes visible, then the full shadow is displayed correctly.
