### ISSUE TITLE
How to animate colors or gradients?

### ISSUE THREAD

**Issue by fschutt** [servo/webrender#3448]
I am a bit stuck on how to implement `:hover` effects without re-building the entire display list. The problem is that I'd like to animate shadows, colors, gradients, etc. - things that don't affect the layout - without re-building the DisplayList. However, right now the main "animation" example only shows the animation of transforms and opacity.

For example, I'd just like to have something like:

```css
#thing { background-color: red; }
#thing:hover { background-color: yellow; }
```

... and then transition from red to yellow by just sending a `Transaction::update_dynamic_property` (without going through all the display list building, etc.). Is this possible, and if yes, how?
