### ISSUE TITLE
rectangle clips don't apply to nested stacking contexts

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#735]
The following yaml file draws incorrectly. We should not see a 100x100 box.

```
---
root:
  items:
    - 
      type: stacking_context
      bounds: [0, 0, 95, 88]
      clip:
        rect: [9, 9, 10, 10]
      items:
        - 
          type: stacking_context
          bounds: [0, 0, 95, 88]
          clip:
              rect: [0, 0, 100, 100]
          items:
            - 
              bounds: [0, 0, 100, 100]
              type: rect
              color: blue
```
