### ISSUE TITLE
rotated things are clipped

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#743]
The following renders as a triangle instead of square
```yaml
---
root:
  items:
    -
      bounds: [0, 0, 400, 400]
      transform: rotate(45)
      items:
        -
          bounds: [100, 100, 100, 100]
          type: rect
          color: blue
      type: stacking_context
```
