### ISSUE TITLE
Content leaks out of mask

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#842]
Try this test using mask.png from the mask directory:

```
---
root:
  items:
    -
      type: stacking_context
      bounds: [0, 0, 95, 88]
      transform: rotate(45)
      items:
        -
          type: scroll_layer
          bounds: [0, 0, 95, 88]
          content-size: [95, 88]
          clip:
            image_mask:
              image: "mask.png"
              rect: [4, 4, 35, 35]
              repeat: false
            rect: [0, 0, 95, 88]
          items:
           -
            bounds: [0, 0, 95, 88]
            type: rect
            color: blue
```

Blue leaks out of the edges.
